CREATE TABLE comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          content TEXT NOT NULL,
                          timestamp TIMESTAMP NOT NULL,
);

CREATE TABLE tickets (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         title VARCHAR(255) NOT NULL,
                         category VARCHAR(50) NOT NULL,
                         priority VARCHAR(50) NOT NULL,
                         summary TEXT NOT NULL,
);

CREATE INDEX idx_tickets_category ON tickets(category);