CREATE TABLE comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          content TEXT NOT NULL,
                          timestamp TIMESTAMP NOT NULL,
                          processed BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE tickets (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         comment_id BIGINT NOT NULL UNIQUE,
                         title VARCHAR(255) NOT NULL,
                         category VARCHAR(50) NOT NULL,
                         priority VARCHAR(50) NOT NULL,
                         summary TEXT NOT NULL,
                         CONSTRAINT fk_ticket_comment FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE
);

CREATE INDEX idx_tickets_category ON tickets(category);
CREATE INDEX idx_comments_processed ON comments(processed);